name = "Typstry"
uuid = "f0ed7684-a786-439e-b1e3-3b82803b501e"
authors = ["Jakob Peters <jakobj.peters@gmail.com>"]
version = "0.1.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Typst_jll = "eb4b1da6-20f6-5c66-9826-fdb8ad410d0e"

[compat]
Artifacts = "1.7"
PrecompileTools = "1"
Typst_jll = "0.2, 0.3, 0.7, 0.8, 0.10, 0.11"
julia = "1.7"
